// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-event-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_event_info_default = defineTool({
  name: "get_event_info",
  title: "Get event info",
  description: "Return public information about the Instal Show 2026 event: dates, location, edition, and description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Instal Show 2026",
      edition: "2\xAA Edi\xE7\xE3o",
      dates: "25 e 26 de Junho de 2026",
      location: "Arca - S\xE3o Paulo, SP, Brasil",
      description: "A maior feira e congresso de instala\xE7\xF5es el\xE9tricas, hidr\xE1ulicas, ar condicionado e prote\xE7\xE3o contra inc\xEAndios do Brasil.",
      website: "https://instalshow.com.br",
      audience: {
        professionals: "3.800+",
        companies: "300+",
        states: 25
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-exhibitors.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var exhibitors = Array.from({ length: 16 }, (_, i) => ({
  id: i + 1,
  name: `Expositor ${i + 1}`
}));
var list_exhibitors_default = defineTool2({
  name: "list_exhibitors",
  title: "List exhibitors",
  description: "List the companies confirmed as exhibitors at Instal Show 2026.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(exhibitors, null, 2) }],
    structuredContent: { total: exhibitors.length, exhibitors }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return contact information for the Instal Show organization (phone, email, location, WhatsApp).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      phone: "+55 11 96383-0660",
      whatsapp: "https://wa.me/5511963830660",
      email: "atendimento@instalshow.com.br",
      location: "Arca - S\xE3o Paulo, SP, Brasil",
      website: "https://instalshow.com.br"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "instalshow-mcp",
  title: "Instal Show MCP",
  version: "0.1.0",
  instructions: "Public MCP server for Instal Show 2026, a Brazilian trade fair for electrical, hydraulic, HVAC and fire-protection installations. Use `get_event_info` for dates, location and audience stats; `list_exhibitors` for the confirmed companies; `get_contact_info` for phone, WhatsApp, email and address.",
  tools: [get_event_info_default, list_exhibitors_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
